# full path to input catalog
catalog: '/Users/jgreco/Downloads/test.csv'

# full path to figure list file
figures: '/Users/jgreco/Desktop/figlist.txt'

# if None (~), will use same path as catalog
out_path: ~ 

# plot parameters
x1: 'g-i'
y1: 'g-r'

x2: 'r_e'
y2: 'mag_auto'

# ra, dec column names
ra_col: 'ra' 
dec_col: 'dec'
